spring:
  #H2 CONFIGURATION
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: ${DATABASE_URL:jdbc:h2:mem:contabilidade}
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#          ddl-auto: update

  #POSTGRES CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/contabilidade-postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

server:
  error:
    include-stacktrace: never

spring-doc:
  swagger-ui:
    path: /
    tagsSorter: alpha
    operationsSorter: method